### PR TITLE
Resolve #651 Insert should not cascade if CascadeAction.SAVE is not s…

### LINKED ISSUE #651: Insert should not cascade if CascadeAction.SAVE is not specified
Hi,

I have a data model with a **Parent** entity that references a **Child** entity (**many-to-one**). The only cascade action specified is DELETE (not SAVE).

```Java
@Entity
public abstract class AbstractParent {
    @Key
    @Generated
    long id;

    @ManyToOne(cascade = CascadeAction.DELETE)
    @ForeignKey(delete = ReferentialAction.SET_NULL)
    AbstractChild child;
}
```

```Java
@Entity
public abstract class AbstractChild {
    @Key
    long id;
}
```

If I try to create a Parent referencing a Child that does not exist in the database, I **would expect the operation to fail** because of a **foreign key constraint violation**, but instead requery cascades the insert.

```Java
Child child = new Child();
child.setId(1);
Parent parent = new Parent();
Parent.setChild(child);

Exception e = null;
EntityDataStore store = ...
try{
   store.insert(parent);
}catch(Exception ex){
   e = ex;
}

assertNotNull(e); // Assert fails
```

Checking the **EntityWriter** code (line 445), it seems to me that **insert** method **should not call cascadeKeyReference if the CascadeAction.SAVE is not present**.

See https://bitbucket.org/mirkoluchi/requery-issues (Issue651Test) for a test case of this issue

### PR DESCRIPTION
**Pull request by mirkoluchi**
…pecified

Modify EntityWriter.insert method to cascade insertion on emtities referenced by foreign key ONLY when CascadeAction.SAVE is specified

### CODE REVIEW

**Comment by mirkoluchi** [comment]
Hi, I checked the Travis error log, but I don't think the issue is related to the code I modified...

**Comment by npurushe** [comment]
The test error is unfortunately caused by the change, however I understand the intent behind the PR. Will look into how this can be handled thanks!

**Comment by mirkoluchi** [comment]
Thanks.
Please let me know the solution.

Anyway, the fix itself isn't the cause. The SchemaModifierTest fails because something in the 2 test entities  (AbstractParent and AbstractChild) I added to the model cause issues to Derby SQL statements...but I don't know why

**Comment by mirkoluchi** [comment]
I found out the issue: *Derby does not support on update cascade*.

I slightly changed the AbstractParent ForeignKey to use a different cascade, and now tests should work.

**Comment by mirkoluchi** [comment]
Hi, the *ParameterizedFunctionalTest.testInsertWithoutCascadeActionSave* that I added now fails for SQLite database, but ** just because in that test class SQLite has foreign key constraints turned off**.

The same test in *SqliteFunctionalTest* works, because in that class the foreign keys constraints are turned on (**PRAGMA foreign_keys = ON**).

Is there a reason why you do not turn on the foreign key constraints on SQLite in the ParameterizedFunctionalTest (in which case I'll move the *testInsertWithoutCascadeActionSave* only in the *SqliteFunctionalTest*, or is it a mistake?

**Comment by npurushe** [comment]
Sqlite foreign keys should be enabled with this statement https://github.com/requery/requery/blob/master/requery-test/src/test/java/io/requery/test/DatabaseType.java#L84 It should be working as other tests are dependent on it. Will look into it thanks

**Comment by mirkoluchi** [comment]
I checked the code and found the reason.

According to SQLite documentation, **foreign key support** must be enabled **on each Connection**, not just once (see https://sqlite.org/foreignkeys.html where it says `Foreign key constraints are disabled by default (for backwards compatibility), so must be enabled separately for each database connection`.

The difference in your test code is that in **ParameterizedFunctionalTest** you **execute _PRAGMA foreign_keys = ON_ only once**, in the DataSource creation (https://github.com/requery/requery/blob/master/requery-test/src/test/java/io/requery/test/DatabaseType.java#L84), while in **SqliteFunctionalTest** you you **execute _PRAGMA foreign_keys = ON_ for each connection**
 (https://github.com/requery/requery/blob/master/requery-android/src/main/java/io/requery/android/sqlite/DatabaseSource.java#L233).

The **SQLiteDataSource** class has a _setEnforceForeinKeys_ methods that makes that for you. I changed your test code to fix the issue and pushed it.

**Comment by mirkoluchi** [comment]
Do you know why Travis build fails because unable to start mysql service?

**Comment by npurushe** [comment]
Thanks for the update looking into this

**Pull request merged**
