### PR TITLE
Resolve #247 Fixed upsert on sqlite

### LINKED ISSUE #247: error on calling upsert on android sqlite
I'm getting an `java.sql.SQLIntegrityConstraintViolationException: UNIQUE constraint failed` when calling upsert on the datastore on Android. I thought that it would do a insert or replace. Is there a way of adding a Constraint on the column to replace on conflict?

### PR DESCRIPTION
**Pull request by rciurkot**
#247 Upsert was not working properly on Android with Sqlite.

Deserialized Entity (eg. obtained from api and deserialized with gson) was not correctly upserted. `update()` method returned `-1` what was not handled inside `upsert()` method.
For not upsert-enabled databases first we force update, then if it nothing was updated, we do `insert()`.

### CODE REVIEW

**Comment by npurushe** [comment]
Please ignore the build failure. Your change is mostly ok, see comments. Thanks!

**Comment by rciurkot** [comment]
@npurushe I can't find any comments

**Comment by npurushe** [comment]
Oh sorry the review comments were still pending and didn't show up

**Comment by rciurkot** [comment]
@npurushe I've made requested changes

**Comment by npurushe** [comment]
Looks like this not working for cascading an upsert and instead inserting when it should be an update

**Comment by npurushe** [comment]
Closing this for now, will look into how to accommodate this while preserving the cascading behavior.

**Comment by andre-artus** [comment]
Would it not be possible to just use SQLite's 'REPLACE" instead of "INSERT"?

**Comment by npurushe** [comment]
Sqlite `insert or replace` deletes the old row before inserting a new row. This might sound ok but if there are foreign keys with cascade delete this would trigger those linked records to get deleted unexpectedly. So unfortunately it's not suitable as an "upsert"

**Pull request closed without merging**
